name: Deploy Terraform

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Select project to deploy"
        required: true
        default: "ec2"
        type: choice
        options:
          - ec2
          - s3

      tag:
        description: "Enter release tag"
        required: false
        default: "latest"

env:
  TERRAFORM_VERSION: 1.5.6
  TFLINT_VERSION: v0.48.0
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          role-session-name: terraform-deploy

      - name: Download and extract release artifact
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.release.tag_name }}
          fileName: terraform-artifact.zip
          out-file-path: ./terraform_code
          extract: true
          latest: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init - EC2
        working-directory: terraform_code/terraform-ec2
        run: terraform init -input=false

      - name: Terraform Init - S3
        working-directory: terraform_code/terraform-s3
        run: terraform init -input=false

      - name: Terraform Apply - EC2
        working-directory: terraform_code/terraform-ec2
        run: terraform apply -auto-approve tfplan-ec2.binary

      - name: Terraform Apply - S3
        working-directory: terraform_code/terraform-s3
        run: terraform apply -auto-approve tfplan-s3.binary
