name: Deploy Terraform

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  TERRAFORM_VERSION: 1.5.6
  AWS_REGION: us-east-1

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          role-session-name: terraform-deploy

      - name: Download and extract release artifact
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.release.tag_name }}
          fileName: terraform-artifact.zip
          out-file-path: ./terraform_code
          extract: true
          latest: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init - EC2
        working-directory: terraform_code/infrastructure/terraform-ec2
        run: terraform init -input=false

      - name: Terraform Init - S3
        working-directory: terraform_code/infrastructure/terraform-s3
        run: terraform init -input=false

      - name: Terraform Plan - EC2
        working-directory: terraform_code/infrastructure/terraform-ec2
        run: terraform plan -out=tfplan-ec2.binary

      - name: Terraform Plan - S3
        working-directory: terraform_code/infrastructure/terraform-s3
        run: terraform plan -out=tfplan-s3.binary

      - name: Terraform Apply - EC2
        working-directory: terraform_code/infrastructure/terraform-ec2
        run: terraform apply -auto-approve tfplan-ec2.binary

      - name: Terraform Apply - S3
        working-directory: terraform_code/infrastructure/terraform-s3
        run: terraform apply -auto-approve tfplan-s3.binary
